### ISSUE TITLE
watchNamespace does not support multiple namespaces

### ISSUE THREAD

**Issue by Utwo** [VictoriaMetrics/operator#678] opened 2023-06-23 08:14 UTC
If I set watchNamespace to "namespace1,namespace2" I get the following error:

```
{"level":"info","ts":1687507932.105281,"msg":"k8s.io/client-go@v12.0.0+incompatible/tools/cache/reflector.go:169: failed to list *v1.PartialObjectMetadata: services is forbidden: User \"system:serviceaccount:victoria-metrics:victoria-metrics-victoria-metrics-operator\" cannot list resource \"services\" in API group \"\" in the namespace \"namespace1,namespace2\"\n"}

{"level":"error","ts":1687507932.1053176,"msg":"k8s.io/client-go@v12.0.0+incompatible/tools/cache/reflector.go:169: Failed to watch *v1.PartialObjectMetadata: failed to list *v1.PartialObjectMetadata: services is forbidden: User \"system:serviceaccount:victoria-metrics:victoria-metrics-victoria-metrics-operator\" cannot list resource \"services\" in API group \"\" in the namespace \"namespace1,namespace2\"\n","stacktrace":"k8s.io/klog/v2.(*loggingT).output\n\tk8s.io/klog/v2@v2.80.1/klog.go:874\nk8s.io/klog/v2.(*loggingT).printDepth\n\tk8s.io/klog/v2@v2.80.1/klog.go:714\nk8s.io/klog/v2.ErrorDepth\n\tk8s.io/klog/v2@v2.80.1/klog.go:1534\nk8s.io/apimachinery/pkg/util/runtime.logError\n\tk8s.io/apimachinery@v0.25.6/pkg/util/runtime/runtime.go:115\nk8s.io/apimachinery/pkg/util/runtime.HandleError\n\tk8s.io/apimachinery@v0.25.6/pkg/util/runtime/runtime.go:109\nk8s.io/client-go/tools/cache.DefaultWatchErrorHandler\n\tk8s.io/client-go@v12.0.0+incompatible/tools/cache/reflector.go:140\nk8s.io/client-go/tools/cache.(*Reflector).Run.func1\n\tk8s.io/client-go@v12.0.0+incompatible/tools/cache/reflector.go:224\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tk8s.io/apimachinery@v0.25.6/pkg/util/wait/wait.go:157\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tk8s.io/apimachinery@v0.25.6/pkg/util/wait/wait.go:158\nk8s.io/client-go/tools/cache.(*Reflector).Run\n\tk8s.io/client-go@v12.0.0+incompatible/tools/cache/reflector.go:222\nk8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1\n\tk8s.io/apimachinery@v0.25.6/pkg/util/wait/wait.go:58\nk8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1\n\tk8s.io/apimachinery@v0.25.6/pkg/util/wait/wait.go:75"}
```

If I set it to just one of the namespace, then everything work fine.

**Comment by f41gh7** [comment] 2023-06-23 12:03
Hello, only `cluster-wide` or `single` namespace mode is supported for now.

 Probably, in future we'll introduce multi-namespace mode. 

 Workaround for now, deployment operator + resources at each namespace. Or use `cluster-wide` mode with objectSelectors.

**Comment by Utwo** [comment] 2023-06-24 10:34
Alright, thank you!

**Comment by hagen1778** [comment] 2023-07-14 14:07
Duplicate of https://github.com/VictoriaMetrics/operator/issues/557

**Closed by hagen1778** 2023-07-14 14:07 UTC
Labels: enhancement
