### ISSUE TITLE
VMNodeScrape selector not works

### ISSUE THREAD

**Issue by CRASH-Tech** [VictoriaMetrics/operator#644] opened 2023-05-15 18:06 UTC
I'm trying to scape metrics only from control-plane nodes, but vmagent scrapes from all nodes.

I was trying this, but it's not work:
```
  selector:
    matchExpressions:
      - key: "node-role.kubernetes.io/control-plane"
        operator: Exists
```
```
  selector:
    matchLabels:
      node-role.kubernetes.io/control-plane: ""
```

**Comment by f41gh7** [comment] 2023-05-15 18:13
Hello, could you add a full example of VMNodeScrape object?

**Comment by CRASH-Tech** [comment] 2023-05-15 18:34
> Hello, could you add a full example of VMNodeScrape object?

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: kubernetes-etcd
spec:
  path: /metrics
  port: "2381"
  scrape_interval: 15s
  selector:
    matchExpressions:
      - key: "node-role.kubernetes.io/control-plane"
        operator: Exists
```

**Comment by CRASH-Tech** [comment] 2023-05-15 18:48
Some news
```
  selector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
```
Do not scrape at all

```
  selector:
    matchLabels:
      node-role.kubernetes.io/control-plane: ""
```
Scrape from all nodes

**Comment by Amper** [comment] 2023-05-17 09:40
Duplicate of #645

**Comment by f41gh7** [comment] 2023-05-24 16:24
An issue must be fixed [v0.34.0](https://github.com/VictoriaMetrics/operator/releases/tag/v0.34.0) release

**Closed by f41gh7** 2023-05-24 16:24 UTC
Labels: bug, duplicate
